### ISSUE TITLE
Open source request

### ISSUE THREAD

**Issue by tanguySnoeck** [Mobile-IoT-Security-Lab/ARMANDroid#1]
Hello,

I have been following your work for some time and find this project really interesting. I would like to integrate it in a project I am working on but the fact that the project is docker contained doesn't make it easy.
Are you considering releasing the source code to allow for better projects integration ?

**Comment by totoR13** [comment]
Hi @tanguySnoeck,
Thank you for the interest.

In this repository you can find all needed files for build the docker image (freely available in [docker hub](https://hub.docker.com/r/totor13/armand)), including the jar file of the ARMANDroid source code. You can you use the jar file or the docker image in accordance to your needed. Alternatively you can contact us in accordance to the license (see [LICENSE](https://github.com/Mobile-IoT-Security-Lab/ARMANDroid/blob/main/LICENCE) or [LICENSE.COMMERCIAL](https://github.com/Mobile-IoT-Security-Lab/ARMANDroid/blob/main/LICENSE.COMMERCIAL)) you are looking for or directly at antonio.ruggia@dibris.unige.it or [alessio.merlo|luca.verderame]@unige.it.

Regards.

**Comment by totoR13** [comment]
Dear @tanguySnoeck
